# This is a basic workflow to help you get started with Actions

name: Secrets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: secret action
          env:# Or as an environment variable
            secret1:${{ secrets.DBHOST }}
            secret3:${{ secrets.DBNAME }}
            secret4:${{ secrets.DBUSER }}
            secret5:${{ secrets.DBPASSWORD }}
            secret2:${{ secrets.DBPORT }}
         run: |
            echo ${{ secrets.DBPASSWORD }}
            echo ${{ secrets.DBUSER }}
            echo ${{ secrets.DBNAME }}
            echo ${{ secrets.DBHOST }}
            echo ${{ secrets.DBPORT }}
