name: Publish Docker image
on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: windows-latest

    steps:

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rasa-actions-server/rasa-bot:latest
          secrets: |
            "secret1=${{ secrets.DBHOST}}"
            "secret2=${{ secrets.DBPORT}}"
            "secret3=${{ secrets.DBNAME}}"
            "secret4=${{ secrets.DBUSER }}"
            "secret5=${{ secrets.DBPASSWORD }}"
            
            
